language: dart
dist: xenial
matrix:
  include:
    - name: Test
      env: COMMAND=test
    - name: Analyze
      env: COMMAND=analyze
addons:
  apt:
    packages:
      - lib32stdc++6
install:
  - git clone https://github.com/flutter/flutter.git -b stable
  - ./flutter/bin/flutter doctor
script:
  - cd src
  - ../flutter/bin/flutter $COMMAND
cache:
  directories:
    - $HOME/.pub-cache
